# Generated by Django 5.2.3 on 2025-06-14 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Esercizio",
            fields=[
                (
                    "nome",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("categoria", models.CharField(max_length=50)),
                ("video", models.CharField(max_length=255)),
                ("descrizione", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "codice_fiscale",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=100)),
                ("nome", models.CharField(max_length=50)),
                ("cognome", models.CharField(max_length=50)),
                ("data_di_nascita", models.DateField()),
                ("genere", models.CharField(max_length=1)),
                ("telefono", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=100)),
                (
                    "immagine",
                    models.ImageField(
                        blank=True, null=True, upload_to="immagini_persone/"
                    ),
                ),
                ("specializzazione", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Paziente",
            fields=[
                (
                    "codice_fiscale",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=100)),
                ("nome", models.CharField(max_length=50)),
                ("cognome", models.CharField(max_length=50)),
                ("data_di_nascita", models.DateField()),
                ("genere", models.CharField(max_length=1)),
                ("telefono", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=100)),
                (
                    "immagine",
                    models.ImageField(
                        blank=True, null=True, upload_to="immagini_persone/"
                    ),
                ),
                ("patologia_da_trattare", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comunica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("contenuto", models.TextField()),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.medico"
                    ),
                ),
                (
                    "paziente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.paziente"
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Seduta",
            fields=[
                (
                    "codice",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("data", models.DateField()),
                ("video", models.CharField(max_length=255)),
                ("evaluate_rt", models.TextField()),
                ("evaluate_pt", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[("sincrono", "Sincrono"), ("asincrono", "Asincrono")],
                        max_length=10,
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.medico"
                    ),
                ),
                (
                    "paziente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.paziente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contiene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "esercizio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.esercizio"
                    ),
                ),
                (
                    "seduta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.seduta"
                    ),
                ),
            ],
            options={
                "unique_together": {("seduta", "esercizio")},
            },
        ),
    ]
