# Generated by Django 5.2.3 on 2025-06-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunica",
            name="mittente",
            field=models.CharField(
                choices=[("medico", "Medico"), ("paziente", "Paziente")],
                default="Medico",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
