# Generated by Django 5.2.3 on 2025-06-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_comunica_mittente"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunica",
            name="letto",
            field=models.BooleanField(default=False),
        ),
    ]
