# Generated by Django 5.2.3 on 2025-06-15 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_medico_user_paziente_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medico",
            name="password",
        ),
        migrations.RemoveField(
            model_name="paziente",
            name="password",
        ),
    ]
