# Generated by Django 5.2.3 on 2025-06-15 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_medico_password_remove_paziente_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Associazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.medico"
                    ),
                ),
                (
                    "paziente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.paziente"
                    ),
                ),
            ],
            options={
                "unique_together": {("paziente", "medico")},
            },
        ),
    ]
