# Generated by Django 5.2.3 on 2025-06-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_associazione"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comunica",
            name="data",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="seduta",
            name="data",
            field=models.DateTimeField(),
        ),
    ]
