# Generated by Django 5.2.3 on 2025-06-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_paziente_patologia_da_trattare"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seduta",
            name="evaluate_pt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="seduta",
            name="evaluate_rt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="seduta",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[("sincrono", "Sincrono"), ("asincrono", "Asincrono")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="seduta",
            name="video",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
