# Generated by Django 5.2.3 on 2025-06-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_seduta_evaluate_pt_alter_seduta_evaluate_rt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="esercizio",
            name="criterio",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
